import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})

AHIR_RELEASE=os.environ['AHIR_RELEASE']
AHIR_INCLUDE=AHIR_RELEASE+"/include"
AHIR_LIB=AHIR_RELEASE+"/lib"


COMPILATION_FLAGS = ' -g -std=gnu11 '

env.Append(CPPPATH = './src/:./include::')
env.Append(CPPPATH = AHIR_INCLUDE)

env.Library('./lib/libFpExecAa', Glob('src/*.c'), CCFLAGS=COMPILATION_FLAGS)
